import type { NextPage } from 'next'
import Head from 'next/head'
import {Footer, Nav} from '../components/general'
import { createTheme, ThemeProvider } from '@mui/material/styles';
import {DrawerLeft} from '../components/reusable'
const theme = createTheme({
  palette: {
    primary: {
      // Purple and green play nicely together.
      main: '#0E0E0E',
    },
    secondary: {
      // This is green.A700 as hex.
      main: '#9A6728',
    },
  },
});
const Home: NextPage = () => {

  return (
    <ThemeProvider theme={theme}>
      <div className='flex flex-col justify-between ' style={{minHeight:'100vh'}}>
        <Head>
          <title>LiveWitch</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav/>
        <DrawerLeft>
          <main><div>dsqdqsdqsdqsdqsd</div></main>
        </DrawerLeft>
        <footer>
          <Footer/>
        </footer>
      </div>
    </ThemeProvider>
  )
}

export default Home
