import type { NextPage } from 'next'
import Head from 'next/head'
import {Nav} from '../components/general'
import styles from '../styles/Home.module.css'
import { createTheme, ThemeProvider } from '@mui/material/styles';

const theme = createTheme({
  palette: {
    primary: {
      // Purple and green play nicely together.
      main: '#0E0E0E',
    },
    secondary: {
      // This is green.A700 as hex.
      main: '#9A6728',
    },
  },
});
const Home: NextPage = () => {

  return (
    <ThemeProvider theme={theme}>
      <div>
        <Head>
          <title>LiveWitch</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className='w-full'>
          <Nav/>
        </header>
        <main className={styles.main}>
          
        </main>
        <footer className={styles.footer}>

        </footer>
      </div>
    </ThemeProvider>
  )
}

export default Home
